### ISSUE TITLE
As a library worker, I want to see the MARC view of a record

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#24] opened 2018-09-21 18:21 UTC
In GitLab by @rkt6 on Mar 29, 2018, 16:08

* [x] I want an easy way to click to the MARC view of a record
* [x] I want it to lie flat on the page, not pop up like some do

(As a product owner, I want the link to be called "MARC view" -- named for what it is, not for who might use it, e.g. "librarian" or "staff")

**Comment by cdmo** [comment] 2019-05-20 19:14
It looks like #227 was a dupe of this, regardless, it is handled by https://github.com/psu-libraries/psulib_blacklight/pull/313

**Closed by cdmo** 2019-05-20 19:14 UTC
