### ISSUE TITLE
Browse: Records not showing up in browse but has browse button and data 

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#1045] opened 2022-08-17 14:26 UTC
Unlike #1044, below records have browse buttons but themselves don't show up in the browse list:

- [ ] `2569268` has button and data but isn't showing up in listing. (this may also be related to the weirdness in the call number?)
- [x] `36488809` has button and data but isn't showing up in listing (2017 and 2015 are)
- [x] `37100122` has button and data but isn't showing up in listing.
- [x] `117030` has button and data, but isn't showing up when you click the button. Interestingly, if you copy in `SB.0409.W8.0009--1980` which is part of the JSON works ok, but if you do `SB.0409.W8` it doesn't show up in the listing https://catalog.libraries.psu.edu/browse/call_numbers?classification=lc&nearby=SB.0409.W8.0009--1980 
- [x] `2448365` has button and data. Not showing up in its own browse, in browse from for `LD.7501.W47D37` or `LD.7501.W47.D37`, as above, does show up for `LD.7501.W47.D37--1915` and does show up in https://catalog.libraries.psu.edu/browse/call_numbers?classification=lc&nearby=LD7501.W47D37+1906+Pamphlet+Box+31 which is from an earlier edition.

Note: This isn't a big problem for the end user since they're likely not looking for _that_ book, but it could also possibly be related to #1043 where items aren't showing up, which is a bigger issue. 
Note: In some other cases, the item itself shows up just above or below the "You're looking for" and this is not a problem

**Comment by ajkiessl** [comment] 2023-04-10 14:49
The four I checked off above work for me.  The first one is likely related to the issue causing https://github.com/psu-libraries/psulib_blacklight/issues/1046.  We are still looking into this.

**Comment by ajkiessl** [comment] 2023-04-10 15:57
@ruthtillman Seems like for `2569268` the issue is being caused by the same issue in #1046.  Since the other four in this issue are working, I'm going to close this and direct to #1046.

**Closed by ajkiessl** 2023-04-10 15:57 UTC
Labels: bug

**Comment by ruthtillman** [comment] 2023-05-11 17:27
Radu's fix solves the one outstanding issue on this.
