### ISSUE TITLE
Viewing nearby items on shelf

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#62] opened 2018-09-21 20:35 UTC
In GitLab by @rkt6 on Jun 26, 2018, 10:28

We need both a link which passes us to a display of Call # browsing and we may consider (for later release) embedding something in the item page or otherwise making a more attractive/engaging display for that browse.

**Comment by ruthtillman** [comment] 2018-10-31 20:04
(this was basically a duplicate of issue #22  )

**Closed** 2018-10-31 20:03 UTC
