### ISSUE TITLE
Indexing tuning

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#258] opened 2019-04-09 17:44 UTC
- [ ] change the `StandardDirectoryFactory` to the `NRTCachingDirectoryFactory`
- [ ] add Transaction Log (TLog)
- [ ] add a commit policy

**Comment by banukutlu** [comment] 2019-04-11 16:31
duplicate of #249

**Closed by banukutlu** 2019-04-11 16:31 UTC
Labels: duplicate
